name: slam-toolbox
version: '0.5.1'
summary: Slam Toolbox
description: |
  A toolbox for building high quality maps of large spaces with a LIDAR.

grade: stable
confinement: devmode
base: core18
type: app

apps:
  slam-toolbox-online-sync:
    command: roslaunch --wait slam_toolbox online_sync.launch
    environment: 
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/lapack:$SNAP/usr/lib/libblas  # pluginlib (lapack, blas)
    plugs: [network, network-bind]

  slam-toolbox-online-async:
    command: roslaunch --wait slam_toolbox online_async.launch
    environment: 
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/lapack:$SNAP/usr/lib/libblas
    plugs: [network, network-bind]

  slam-toolbox-offline:
    command: roslaunch --wait slam_toolbox offline.launch
    environment: 
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/lapack:$SNAP/usr/lib/libblas
    plugs: [network, network-bind]

  # rviz:
  #   command: desktop-launch $SNAP/opt/ros/kinetic/lib/rviz/rviz -d $ROS_PACKAGE_PATH/slam_toolbox/config/slam_toolbox_default.rviz
  #   environment:
  #     LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/OGRE-1.9.0 # rviz plugin (ogre)
  #   plugs: [network, network-bind, home, x11, opengl]

  roscore:
    command: roscore
    plugs: [network, network-bind]

parts:
  workspace:
    build-packages: [libqt5core5a, libqt5widgets5]
    plugin: catkin
    source-space: src
    include-roscore: true
    source: .
    catkin-ros-master-uri: http://localhost:11311
    catkin-packages: [slam_toolbox] #rviz
    recursive-rosinstall: false
    #after: [desktop-qt5]
